### PR TITLE
react-hot loader

### PR DESCRIPTION
**Pull request by frnk94**
Hot-loading replacement module dosen't work for me without this...

### CODE REVIEW

**Comment by lvarayut** [comment]
Thanks for your PR. However, I don't think we need the `react-hot-loader` module as it is deprecated in favor of  `React Transform`. I already [integrated the React Transform](https://github.com/lvarayut/relay-fullstack/blob/master/.babelrc#L7) and it's working very well. Not sure what doesn't work for you.

**Comment by frnk94** [comment]
image

Im not sure what causing this issue then cause I npm installed and it cant hot-reload :/

**Comment by frnk94** [comment]
@lvarayut Thanks
It was an ENV issue... I used dev instead of development and forgot to changed it on .babelrc  😅

**Comment by lvarayut** [comment]
Glad you figured it out :smile:

**Pull request closed without merging**
