### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by caioflores**

### CODE REVIEW

**Comment by caioflores** [comment]
Wrong located pull request! It was supposed to be in our fork, not here.
Sry.

**Comment by Neitsch** [comment]
Some of those features are very cool though. Would you mind making a PR that adds i18n and Relay Modern to this repository? You guys already figured out how to set all that up correctly!

(Side note: I'd recommend keeping package-lock.json or yarn.lock around to pin dependencies)

**Comment by caioflores** [comment]
@Neitsch Yes we can make it! I'll try to make the i18n PR today, we'll try to make the Relay's PR tomorrow, and you can comment on our changes.
We're finishing our boilerplate, we're adding somethings that will be useful for us, I'll update the README file so you can see what you think is interesting for this project and we can PR.

Thanks for the suggestion!

**Comment by Neitsch** [comment]
Awesome, really appreciate that! 👍

**Pull request closed without merging**
