### PR TITLE
altered npm start command to call subtask to allow it to work on windows

### PR DESCRIPTION
**Pull request by claym**
I can't promise this works on other platforms :)

### CODE REVIEW

**Comment by lvarayut** [comment]
Thanks for the great PR. Could you change the branch to `canary` instead of master, you should be able to do so by clicking the `lvarayut:master` at the top and change it to `lvarayut:canary`?

**Comment by claym** [comment]
done

**Comment by lvarayut** [comment]
Thanks, you said previously that you got an error when you run `npm start`. Could you share the error that you got before?

**Comment by claym** [comment]
It's the same error from here: https://github.com/lvarayut/relay-fullstack/issues/53#issuecomment-313258665

Schema has been regenerated
'.' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lvarayut** [comment]
Thanks for clarifying, I just tested on MacOS and worked just fine 👍

**Pull request merged**
