### PR TITLE
Updates webpack@2.2.0 and fixes HMR support

### PR DESCRIPTION
**Pull request by ncrmro**
Here we go!

### CODE REVIEW

**Comment by lvarayut** [comment]
Thanks so much @ncrmro. Let me know if you would you like to be a core "Collaborator" to help maintaining and improving Relay Fullstack 😃

**Comment by ncrmro** [comment]
@lvarayut hehe I'd love too, thank you!

Been working on a project that uses relay-fullstack and uses django so I've actually been bringing stuff I've been working on over there here as well like jwt token support.

**Comment by lvarayut** [comment]
Just send an invitation to you 😄  Please feel free to add/update features as you feel right, make it as your own project 💯

**Comment by Neitsch** [comment]
I'm seeing the following error on canary since this commit
> React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.

Any ideas to fix?

**Comment by ncrmro** [comment]
@Neitsch Yep missed adding `'react-hot-loader/patch'` to the webpack config. Apologies! Fix was made.

**Pull request merged**
